# Twitter API authentication
twitterSecretName: twitter-api

# If consumerKey = controll a secret is not created
# and it assumed that a pre-created secret exsists
# with a the .Values.secret-name specified here.
consumerKey: controll
consumerSecret: null
accessToken: null
accessTokenSecret: null
filterText: Seattle

# Azure
plan: standard-s1
resourceGroup: twitter-sentiment